Squash commits
actions/checkout@v4
add arm64 for linux/osx

macos-13 available

add ubuntu-24.04-arm

/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/_stdio.h:318:7: error: expected ')'

unused

Update README.md
github user